<?php
echo "<H3>list of all dadospessoais items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>nome</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->dadospessoais_items as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->nome</TD>";
    echo "<TD class='admin'><a href='/admin/dadospessoais/modify/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/dadospessoais/delete/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=106 id=_-kOg4KxUEd68D_d-n4iFew_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=106
