CREATE TABLE [dbo].[CATEGORIA] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[ID_TIPO_CATEGORIA] [int] NOT NULL ,
	[ID_CATEGORIA_PAI] [int] NULL ,
	[NIVEL] [int] NOT NULL ,
	[NOME] [varchar] (100) COLLATE Latin1_General_CI_AI NOT NULL ,
	[DESCRICAO] [varchar] (2000) COLLATE Latin1_General_CI_AI NULL ,
	[ATIVO] [bit] NOT NULL ,
	[ROWINFO] [varchar] (2000) COLLATE Latin1_General_CI_AI NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DADOS_PESSOAIS] (
	[ID] [int] NOT NULL ,
	[ID_PESSOA] [int] NOT NULL ,
	[NOME] [varchar] (100) COLLATE Latin1_General_CI_AI NOT NULL ,
	[ROWINFO] [varchar] (2000) COLLATE Latin1_General_CI_AI NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[EMAIL] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[ID_PESSOA] [int] NOT NULL ,
	[ID_CATEGORIA] [int] NOT NULL ,
	[UNIQUE_ID] [varchar] (100) COLLATE Latin1_General_CI_AI NOT NULL ,
	[EMAIL] [varchar] (100) COLLATE Latin1_General_CI_AI NOT NULL ,
	[VALIDADO] [bit] NOT NULL ,
	[DATAHORA_ULTIMA_VALIDACAO] [datetime] NULL ,
	[ATIVO] [bit] NOT NULL ,
	[ROWINFO] [varchar] (2000) COLLATE Latin1_General_CI_AI NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LOG] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[ID_CATEGORIA] [int] NOT NULL ,
	[ID_PERFIL_PESSOA] [int] NOT NULL ,
	[DATAHORA_EVENTO] [datetime] NOT NULL ,
	[XML] [varchar] (2000) COLLATE Latin1_General_CI_AI NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LOGIN] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[ID_PESSOA] [int] NOT NULL ,
	[LOGIN] [varchar] (100) COLLATE Latin1_General_CI_AI NOT NULL ,
	[SENHA] [varchar] (100) COLLATE Latin1_General_CI_AI NOT NULL ,
	[ATIVO] [bit] NOT NULL ,
	[TENTATIVAS_FALHAS] [int] NOT NULL ,
	[TRAVADO] [bit] NOT NULL ,
	[RESETADO] [bit] NOT NULL ,
	[DATAHORA_ULTIMO_LOGON] [datetime] NULL ,
	[OBSERVACOES] [varchar] (2000) COLLATE Latin1_General_CI_AI NOT NULL ,
	[PODE_EXPIRAR] [bit] NOT NULL ,
	[DATAHORA_PROXIMA_EXPIRACAO] [datetime] NULL ,
	[DATAHORA_ULTIMA_EXPIRACAO] [datetime] NULL ,
	[ROWINFO] [varchar] (2000) COLLATE Latin1_General_CI_AI NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PERFIL] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[ID_CATEGORIA] [int] NOT NULL ,
	[NOME] [varchar] (100) COLLATE Latin1_General_CI_AI NOT NULL ,
	[DESCRICAO] [varchar] (2000) COLLATE Latin1_General_CI_AI NULL ,
	[ATIVO] [bit] NOT NULL ,
	[ROWINFO] [varchar] (2000) COLLATE Latin1_General_CI_AI NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PESSOA] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[ROWINFO] [varchar] (2000) COLLATE Latin1_General_CI_AI NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PESSOAS_PERFIS] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[ID_PESSOA] [int] NOT NULL ,
	[ID_PERFIL] [int] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TIPO_CATEGORIA] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[NOME] [varchar] (100) COLLATE Latin1_General_CI_AI NOT NULL ,
	[DESCRICAO] [varchar] (2000) COLLATE Latin1_General_CI_AI NULL ,
	[ROWINFO] [varchar] (2000) COLLATE Latin1_General_CI_AI NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CATEGORIA] WITH NOCHECK ADD 
	CONSTRAINT [PK_CATEGORIA] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[DADOS_PESSOAIS] WITH NOCHECK ADD 
	CONSTRAINT [PK_DADOS_PESSOAIS] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[EMAIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_EMAIL] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LOG] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOG] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LOGIN] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOGIN] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_PERFIL] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PESSOA] WITH NOCHECK ADD 
	CONSTRAINT [PK_PESSOA] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PESSOAS_PERFIS] WITH NOCHECK ADD 
	CONSTRAINT [PK_PESSOAS_PERFIS] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TIPO_CATEGORIA] WITH NOCHECK ADD 
	CONSTRAINT [PK_TIPO_CATEGORIA] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CATEGORIA] ADD 
	CONSTRAINT [DF_CATEGORIA_NIVEL] DEFAULT (1) FOR [NIVEL],
	CONSTRAINT [DF_CATEGORIA_ATIVO] DEFAULT (1) FOR [ATIVO]
GO

CREATE INDEX [IX_CATEGORIA] ON [dbo].[CATEGORIA]([NOME]) ON [PRIMARY]
GO

 CREATE  INDEX [IX_DADOS_PESSOAIS] ON [dbo].[DADOS_PESSOAIS]([NOME]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EMAIL] ADD 
	CONSTRAINT [DF_EMAIL_VALIDADO] DEFAULT (0) FOR [VALIDADO],
	CONSTRAINT [DF_EMAIL_ATIVO] DEFAULT (0) FOR [ATIVO]
GO

 CREATE  UNIQUE  INDEX [IX_EMAIL] ON [dbo].[EMAIL]([UNIQUE_ID]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [IX_EMAIL_1] ON [dbo].[EMAIL]([EMAIL]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOGIN] ADD 
	CONSTRAINT [DF_LOGIN_ATIVO] DEFAULT (0) FOR [ATIVO],
	CONSTRAINT [DF_LOGIN_TENTATIVAS_FALHAS] DEFAULT (0) FOR [TENTATIVAS_FALHAS],
	CONSTRAINT [DF_LOGIN_TRAVADO] DEFAULT (0) FOR [TRAVADO],
	CONSTRAINT [DF_LOGIN_RESETADO] DEFAULT (0) FOR [RESETADO],
	CONSTRAINT [DF_LOGIN_PODE_EXPIRAR] DEFAULT (1) FOR [PODE_EXPIRAR],
	CONSTRAINT [DF_LOGIN_DATAHORA_PROXIMA_EXPIRACAO] DEFAULT (dateadd(month,12,getdate())) FOR [DATAHORA_PROXIMA_EXPIRACAO],
	CONSTRAINT [IX_LOGIN_1] UNIQUE  NONCLUSTERED 
	(
		[ID]
	)  ON [PRIMARY] 
GO

 CREATE  UNIQUE  INDEX [IX_LOGIN] ON [dbo].[LOGIN]([LOGIN]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PERFIL] ADD 
	CONSTRAINT [DF_PERFIL_ATIVO] DEFAULT (1) FOR [ATIVO]
GO

ALTER TABLE [dbo].[PESSOAS_PERFIS] ADD 
	CONSTRAINT [IX_PESSOAS_PERFIS] UNIQUE  NONCLUSTERED 
	(
		[ID_PESSOA],
		[ID_PERFIL]
	)  ON [PRIMARY] 
GO

 CREATE  UNIQUE  INDEX [IX_TIPO_CATEGORIA] ON [dbo].[TIPO_CATEGORIA]([NOME]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CATEGORIA] ADD 
	CONSTRAINT [FK_CATEGORIA_CATEGORIA] FOREIGN KEY 
	(
		[ID_CATEGORIA_PAI]
	) REFERENCES [dbo].[CATEGORIA] (
		[ID]
	),
	CONSTRAINT [FK_CATEGORIA_TIPO_CATEGORIA] FOREIGN KEY 
	(
		[ID_TIPO_CATEGORIA]
	) REFERENCES [dbo].[TIPO_CATEGORIA] (
		[ID]
	)
GO

ALTER TABLE [dbo].[DADOS_PESSOAIS] ADD 
	CONSTRAINT [FK_DADOS_PESSOAIS_PESSOA] FOREIGN KEY 
	(
		[ID]
	) REFERENCES [dbo].[PESSOA] (
		[ID]
	)
GO

ALTER TABLE [dbo].[EMAIL] ADD 
	CONSTRAINT [FK_EMAIL_CATEGORIA] FOREIGN KEY 
	(
		[ID_CATEGORIA]
	) REFERENCES [dbo].[CATEGORIA] (
		[ID]
	),
	CONSTRAINT [FK_EMAIL_PESSOA] FOREIGN KEY 
	(
		[ID_PESSOA]
	) REFERENCES [dbo].[PESSOA] (
		[ID]
	)
GO

ALTER TABLE [dbo].[LOG] ADD 
	CONSTRAINT [FK_LOG_CATEGORIA] FOREIGN KEY 
	(
		[ID_CATEGORIA]
	) REFERENCES [dbo].[CATEGORIA] (
		[ID]
	),
	CONSTRAINT [FK_LOG_PESSOAS_PERFIS] FOREIGN KEY 
	(
		[ID_PERFIL_PESSOA]
	) REFERENCES [dbo].[PESSOAS_PERFIS] (
		[ID]
	)
GO

ALTER TABLE [dbo].[LOGIN] ADD 
	CONSTRAINT [FK_LOGIN_PESSOA] FOREIGN KEY 
	(
		[ID_PESSOA]
	) REFERENCES [dbo].[PESSOA] (
		[ID]
	)
GO

ALTER TABLE [dbo].[PERFIL] ADD 
	CONSTRAINT [FK_PERFIL_CATEGORIA] FOREIGN KEY 
	(
		[ID_CATEGORIA]
	) REFERENCES [dbo].[CATEGORIA] (
		[ID]
	)
GO

ALTER TABLE [dbo].[PESSOAS_PERFIS] ADD 
	CONSTRAINT [FK_PESSOAS_PERFIS_PERFIL] FOREIGN KEY 
	(
		[ID_PERFIL]
	) REFERENCES [dbo].[PERFIL] (
		[ID]
	),
	CONSTRAINT [FK_PESSOAS_PERFIS_PESSOA] FOREIGN KEY 
	(
		[ID_PESSOA]
	) REFERENCES [dbo].[PESSOA] (
		[ID]
	)
GO

