<?php
echo "<H3>list of all anexomensagem items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>nomeoriginal</TD>";
echo "<TD class='header'>nomesugestao</TD>";
echo "<TD class='header'>descricao</TD>";
echo "<TD class='header'>arquivo</TD>";
echo "<TD class='header'>mimetype</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->anexomensagem_items as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->nomeoriginal</TD>";
    echo "<TD class='admin'>$item->nomesugestao</TD>";
    echo "<TD class='admin'>$item->descricao</TD>";
    echo "<TD class='admin'>$item->arquivo</TD>";
    echo "<TD class='admin'>$item->mimetype</TD>";
    echo "<TD class='admin'><a href='/admin/anexomensagem/modify/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/anexomensagem/delete/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=142 id=_bDB3EMSvEd6vnL5X62mZVw_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=142
