<?php
echo "<H3>list of all anexoMensagem items for the mensagem with ID </H3>";
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>nomeoriginal</TD>";
echo "<TD class='header'>nomesugestao</TD>";
echo "<TD class='header'>descricao</TD>";
echo "<TD class='header'>arquivo</TD>";
echo "<TD class='header'>mimetype</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->anexoMensagems as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->nomeoriginal</TD>";
    echo "<TD class='admin'>$item->nomesugestao</TD>";
    echo "<TD class='admin'>$item->descricao</TD>";
    echo "<TD class='admin'>$item->arquivo</TD>";
    echo "<TD class='admin'>$item->mimetype</TD>";
    echo "<TD class='admin'><a href='/admin/mensagem/modifyanexoMensagem/mensagemid/$item->mensagem/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/mensagem/deleteanexoMensagem/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=156 id=_iJJMosoqEd6v-rwJANCYjQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=156
