<?php
echo "<H3>list of all mensagem items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>remetente</TD>";
echo "<TD class='header'>destinatario</TD>";
echo "<TD class='header'>assunto</TD>";
echo "<TD class='header'>datahora</TD>";
echo "<TD class='header'>mensagem</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->mensagem_items as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->remetente</TD>";
    echo "<TD class='admin'>$item->destinatario</TD>";
    echo "<TD class='admin'>$item->assunto</TD>";
    echo "<TD class='admin'>$item->datahora</TD>";
    echo "<TD class='admin'>$item->mensagem</TD>";
    echo "<TD class='admin'><a href='/admin/mensagem/modify/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/mensagem/delete/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=151 id=_kDO0oMIwEd6r_uu4CwoKLQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=151
