<?php
// First, set the action on the form
$this->form->setAction($this->url(array('action' => 'modify')));
echo "<h3>Modify an existing mensagem item</h3>";
echo $this->form;

echo "<a href='/admin/mensagem/addanexoMensagem/mensagemid/".$this->mensagemid."/'>Add anexoMensagems</a>";
echo $this->render('/mensagem/indexanexoMensagems.phtml');

//#BlockStart number=132 id=_kDO0oMIwEd6r_uu4CwoKLQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=132
