<?php
// First, set the action on the form
$this->form->setAction($this->url(array('action' => 'modify')));
echo "<h3>Modify an existing pessoa item</h3>";
echo $this->form;

echo "<a href='/admin/pessoa/addemails/pessoaid/".$this->pessoaid."/'>Add emailss</a>";
echo $this->render('/pessoa/indexemailss.phtml');

//#BlockStart number=6 id=_ej5KYKoDEd687LtTWUTtuQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=6
