<?php
echo "<H3>list of all termtranslation items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>language</TD>";
echo "<TD class='header'>translate nl</TD>";
echo "</TR>";
foreach($this->termtranslation_items as $item)
{
    echo "<TR>";
    echo "<TD class='admin'>$item->name</TD>";
    echo "<TD class='admin'><a href='/admin/termtranslation/modify/language/$this->language/id/$item->id'>translate $this->language</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=109 id=_16_5_1_40d01a2_1250796841411_723745_449_#_0

//start block for manually written code

//end block for manually written code

//#BlockEnd number=109
