<?php
echo "<H3>list of all mensagememail items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>destinatarioscopiacarbonada</TD>";
echo "<TD class='header'>destinatarioscopiacarbonadacega</TD>";
echo "<TD class='header'>responderpara</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->mensagememail_items as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->destinatarioscopiacarbonada</TD>";
    echo "<TD class='admin'>$item->destinatarioscopiacarbonadacega</TD>";
    echo "<TD class='admin'>$item->responderpara</TD>";
    echo "<TD class='admin'><a href='/admin/mensagememail/modify/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/mensagememail/delete/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=142 id=_l3UeAK0fEd6Tgc0yakCadQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=142
