<?php
echo "<H3>list of all log items for the categoria with ID </H3>";
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>datahoraevento</TD>";
echo "<TD class='header'>xml</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->logs as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->datahoraevento</TD>";
    echo "<TD class='admin'>$item->xml</TD>";
    echo "<TD class='admin'><a href='/admin/categoria/modifylog/categoriaid/$item->categoria/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/categoria/deletelog/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=54 id=_1xWkwaxOEd68D_d-n4iFew_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=54
