<?php
echo "<H3>list of all categoria items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>nivel</TD>";
echo "<TD class='header'>nome</TD>";
echo "<TD class='header'>descricao</TD>";
echo "<TD class='header'>ativo</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->categoria_items as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->nivel</TD>";
    echo "<TD class='admin'>$item->nome</TD>";
    echo "<TD class='admin'>$item->descricao</TD>";
    echo "<TD class='admin'>$item->ativo</TD>";
    echo "<TD class='admin'><a href='/admin/categoria/modify/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/categoria/delete/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=43 id=_0N60kKoIEd687LtTWUTtuQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=43
