<?php
echo $this->doctype('HTML4_LOOSE');
?>
<html>
<head>
<?php echo $this->headTitle();?>
<?php echo $this->headMeta();?>
<?php echo $this->headLink();?>
<?php echo $this->headScript();?>
<?php echo $this->inlineScript();?>
</head>
<body>
<a href='http://www.bozasolutions.com'>
<img alt="BOZA logo" src="/public/default/img/boza_logo.jpg" width='300px'>
</a>
<h3>BOZA Solutions - Web & software development</h3>
<?php
/*echo "<div id='menu'>";
foreach($this->menus as $menu)
{
    echo "<div class='glink'><a href='/index'>$menu->caption</a></div>";
}
echo "<div>";
*/
?>
<br><br><br><br>
<div id='content'>
<?php echo $this->layout()->content?>
</div>
<div id='footer'>
<?php echo $this->render('footer.phtml')?>
</div>
</body>
</html>
