<?php
echo $this->doctype('HTML4_LOOSE');
?>
<html>
<head>
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta()    ?>
<?php echo $this->headLink()  ?>
<?php echo $this->headScript() ?>

</head>
<body onload="setUpFCK()">
<a href="/admin"><img
    src="/public/admin/img/boza_logo.jpg"
    style="position: absolute; left: 7px; top: 2px; width: 170px"></a>
<div id='showing_menu_bar' <?php if(isset($_SESSION["showing"]) && $_SESSION["showing"] == 1) echo "style='display:none;'"; else echo ""; ?>>
    <div id='inner_block'></div>
    <a href='javascript:void(0);' id='show_menu'></a>
</div>
<div id='left_region' <?php if(isset($_SESSION["showing"]) && $_SESSION["showing"] == 1) echo ""; else echo "style='display:none;'"; ?>>
<a id='hide_menu' href='javascript:void(0);'  class='hiding' title='hide navigation menu'></a>
<div class='cb'></div>
<div id='menu_item'>
<h3>Site Admin</h3>
</div>

<?php
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity())
{
    foreach($this->adminmenus as $menu)
    {
        echo "<div id='menu_item'><a href='/admin/$menu->controller/$menu->action'>$menu->caption</a></div>";
        if($this->controller==$menu->controller)
            foreach($this->adminsubmenus as $submenu)
                echo "<div id='submenu_item'><a href='/admin/$submenu->controller/$submenu->action'>$submenu->caption</a><br></div>";
    }
    echo "<div id='menu_item'><a href='/admin/login/logout'>Logout</a></div>";
}
?></div>
<div <?php if(isset($_SESSION["showing"]) && $_SESSION["showing"] == 1) echo "id='content'"; else echo "id='content2'"; ?>>
<?php
if($this->controller=='termtranslation')
{
    echo "Current language: ".strtoupper($this->language);
    echo "<div style='position:absolute;right:10px;top:0px;'>";
    echo "<a href='/admin/$this->controller/index/language/nl'>NL</a> | ";
    echo "<a href='/admin/$this->controller/index/language/en'>EN</a> | ";
    echo "<a href='/admin/$this->controller/index/language/fr'>FR</a>";
    echo "</div>";
}
echo $this->openDecoration();
echo $this->layout()->content;
echo $this->closeDecoration();
?></div>
</body>
</html>
