<?php 
/**
 * Layout padrão do sistema.
 */

$applicationHttpHome = $this->urlEncrypt($this->url(array('controller'=>'index'), null, true));
$applicationHttpImagesHome = $this->baseUrl('/images/');
$applicationHttpCSSHome = $this->baseUrl('/css/global.css');
$applicationHttpBaseUrl = $this->baseUrl();

$this->doctype('XHTML1_STRICT');
$this->headTitle(APPLICATION_NAME_AND_VERSION);
$this->headTitle()->setSeparator(' - ');
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headLink()->appendStylesheet($applicationHttpCSSHome);

if (Basico_UtilControllerController::ambienteDesenvolvimento())
{
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $requestTitle = '('.$request->getModuleName().': '.$request->getControllerName().'/'.$request->getActionName().')';    
    $this->headTitle($requestTitle);
}
?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?> 
    <style type="text/css">
         body, html { 
            font-family:helvetica,arial,sans-serif; 
            font-size:90%; 
            text-decoration: none;
         }
         
         body, html a { 
            text-decoration: none;
         }
    </style>
    <?php
        $this->dojo()->setDjConfig(array('usePlainJson' => true, 'locale' => Basico_PessoaControllerController::retornaLinguaUsuario()))
                     ->addStylesheetModule(DOJO_STYLE_SHEET_MODULE)
                     ->setLocalPath($applicationHttpBaseUrl . DOJO_LOCAL_PATH)
                     ->addLayer($applicationHttpBaseUrl . DEFAULT_JAVASCRIPT_FILE_PATH);    
        $this->dojo()->requireModule('dijit.Dialog');
        
        echo $this->dojo();
    ?>
    <?php echo $this->headScript()?>
   
</head> 
<body class="rochedo">
<div class="loading"></div>
<div id="header">
    <div id="header-logo">
           <?php echo "<a onClick='loading()' href=" . "'" . $applicationHttpHome."'".">" . APPLICATION_NAME_AND_VERSION . "</a>" ?>
    </div>
    <div id="header-navigation">
        <a onClick="loading()" href="<?php echo $this->urlEncrypt($this->url(
                                                         array('module'=>'basico', 'controller'=>'login', 'action'=>'cadastrarUsuarioNaoValidado'), 
                                                         null, 
                                                         true)) ?>"><?php echo $this->tradutor(MENU_ITEM_REGISTRE_SE) ?></a> |
		<a onClick="loading()" href="<?php echo $this->urlEncrypt($this->url(
                                                         array('module'=>'basico', 'controller'=>'dadosusuario', 'action'=>'dadosusuario'), 
                                                         null, 
                                                         true)) ?>"><?php echo "Meu Perfil" ?></a> |
		<a onClick="loading()" href="<?php echo $this->urlEncrypt($this->url(
                                                         array('module'=>'basico', 'controller'=>'geradorformulario', 'action'=>'gerarformulario'), 
                                                         null, 
                                                         true)) ?>"><?php echo "Gerador de Formularios" ?></a> |
        <a onClick="loading()" href="<?php echo $this->urlEncrypt($this->url(
                                                         array('module'=>'basico', 'controller'=>'administrador', 'action'=>'index'), 
                                                         null, 
                                                         true)) ?>"><?php echo "Administração" ?></a>                                                
    </di                                                         
    </div>
</div>

<br>

<div id="content">
<?php echo $this->layout()->content ?>
</div>

<br>

<div id="footer">
	<br>
	<div id="footer_poweredby">
		<a href="http://framework.zend.com/" target="_blank" ><img alt="Powered by ZendFramework" src="<?php echo $applicationHttpImagesHome . 'zf/PoweredBy_ZF_4LightBG.png' ?>" /></a>
	</div> 
</div>

</body>
</html>
