<?php 
/**
 * Layout padrão do sistema.
 */
?>
<!--[if IE 8]> <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9]> <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>    
	<?php
	// enviando ao cliente as informacoes sobre do cabecalho do documento html
	echo $this->headTitle();
	echo $this->headMeta();
	echo $this->headLink();

	// setando o dojo e jquery
	echo $this->dojo();
	echo $this->jQuery();
	
    echo $this->headScript();
    
    // recuperando variaveis da view
    $scripts  = Basico_OPController_AcaoAplicacaoAssocVisaoOPController::SCRIPTS;
    $content  = Basico_OPController_AcaoAplicacaoAssocVisaoOPController::CONTENT;
    $metadata = Basico_OPController_AcaoAplicacaoAssocVisaoOPController::METADATA;
    $header   = Basico_OPController_AcaoAplicacaoAssocVisaoOPController::HEADER;
    $footer   = Basico_OPController_AcaoAplicacaoAssocVisaoOPController::FOOTER;
    
    // recuperando os scripts incluidos na view
   	$scriptsContent = $this->$scripts;

   	// verificando se o scripts eh array
	if (is_array($scriptsContent)) {
		// loop para enviar os scripts
		foreach ($scriptsContent as $key => $value) {
			// enviando script
			echo $value;		
		}
	} else {
		// enviando scripts
		echo $scriptsContent;
	}
    ?>
</head>

<body class="rochedo">

<div class="loading"></div>
<div id="header">
<?php 
	// recupera o conteudo do placeholder headerMenu
	$headerMenu = $this->placeholder("headerMenu")->getValue();
	// verifica se algo foi escrito
	if(!empty($headerMenu)) {
		echo $this->placeholder("headerMenu");
	}


	$scriptsContent = $this->$header;
	
	if (is_array($scriptsContent)) {
		foreach ($scriptsContent as $key => $value) {
			echo $value;		
		}
	} else {
		echo $scriptsContent;
	}

?>   
</div>
<div id="content">
<?php
	// recupera o conteudo do placeholder content
	$metadataValue = $this->placeholder($metadata)->getValue();
	// verifica se algo foi escrito
	if(!empty($metadataValue)) {
		echo $this->placeholder($metadata);
	}

	// recupera o conteudo do placeholder content
	$contentValue = $this->placeholder($content)->getValue();
	// verifica se algo foi escrito
	if(!empty($contentValue)) {
		echo $this->placeholder($content);
	}
?>
</div>

<br>
<div id="footer">
<?php 

	$scriptsContent = $this->$footer;
	
	if (is_array($scriptsContent)) {
		foreach ($scriptsContent as $key => $value) {
			echo $value;		
		}
	} else {
		echo $scriptsContent;
	}
	// recupera o conteudo do placeholder footer
	$footerValue = $this->placeholder($footer)->getValue();
	// verifica se algo foi escrito
	if(!empty($footerValue)) {
		echo $this->placeholder($footer);
	}
?>   
</div>

</body>
</html>
