<?php
// First, set the action on the form
$this->form->setAction($this->url(array('action' => 'modify')));
echo "<h3>Modify an existing pessoasperfis item</h3>";
echo $this->form;

echo "<a href='/admin/pessoasperfis/addlog/pessoasperfisid/".$this->pessoasperfisid."/'>Add logs</a>";
echo $this->render('/pessoasperfis/indexlogs.phtml');

//#BlockStart number=75 id=_nKZzkKoLEd687LtTWUTtuQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=75
