<?php
echo "<H3>list of all email items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>uniqueid</TD>";
echo "<TD class='header'>email</TD>";
echo "<TD class='header'>validado</TD>";
echo "<TD class='header'>datahoraultimavalidacao</TD>";
echo "<TD class='header'>ativo</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->email_items as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->uniqueid</TD>";
    echo "<TD class='admin'>$item->email</TD>";
    echo "<TD class='admin'>$item->validado</TD>";
    echo "<TD class='admin'>$item->datahoraultimavalidacao</TD>";
    echo "<TD class='admin'>$item->ativo</TD>";
    echo "<TD class='admin'><a href='/admin/email/modify/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/email/delete/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=25 id=_oQ1w0KoDEd687LtTWUTtuQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=25
