<?php

$tituloView = $this->tradutor(TITULO_REENVIO_EMAIL_CONFIRMACAO_NOVO_USUARIO, DEFAULT_USER_LANGUAGE);
$subtituloView = $this->tradutor(SUBTITULO_REENVIO_EMAIL_CONFIRMACAO_NOVO_USUARIO, DEFAULT_USER_LANGUAGE);
$mensagemView = $this->tradutor(MENSAGEM_REENVIO_EMAIL_CONFIRMACAO_NOVO_USUARIO, DEFAULT_USER_LANGUAGE);

echo <<<TEXT
<h3>{$tituloView}</h3>
<h4>{$subtituloView}<h4>
<h5>{$mensagemView}</h5>
TEXT;
