<?php 
/**
 * View Padrão para erros do sistema.
 */
$applicationHttpImagesHome = $this->baseUrl('/images/');

?>
<h1>Infelizmente aconteceu um erro.</h1>
<h2><?= $this->message ?></h2>
<pre>Informe ao <a href="mailto:<?php echo SUPPORT_EMAIL ?>">suporte</a> seu login e data/hora do erro (<b><?php echo date('d/m/Y H:i:s'); ?></b>)
</pre>

<?php if (Basico_UtilControllerController::ambienteDesenvolvimento()): ?>
<hr />
<h1>** DEBUG INFO **</h1>

<h3>Informa&ccedil;&otilde;es do Exception:</h3>
<p>
  <b>Message:</b> <?= $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre><?= $this->exception->getTraceAsString() ?>
</pre>

<h3>Parametros do Request:</h3>
<pre><? var_dump($this->request->getParams()) ?>
</pre>
<h3>Croco erro:</h3>
<img alt="Crocro error!" src="<?php echo $applicationHttpImagesHome . 'temp/excited-crocodile.jpg' ?>"/>
<pre>crocodilagem...</pre>
<? endif ?>