<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
  <h1>Infelizmente aconteceu um erro.</h1>
  <h2><?= $this->message ?></h2>

  <pre>Informe ao <a href="mailto:<?php echo SUPPORT_EMAIL ?>">suporte</a> seu login e data/hora do erro (<b><?php echo date('d/m/Y H:i:s'); ?></b>)
  </pre>

  <? if (Basico_Model_Util::ambienteDesenvolvimento()): ?>
  <hr />
  <h1>** DEBUG INFO **</h1>

  <h3>Informa&ccedil;&otilde;es do Exception:</h3>
  <p>
      <b>Message:</b> <?= $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?= $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Parametros do Request:</h3>
  <pre><? var_dump($this->request->getParams()) ?>
  </pre>
  <? endif ?>

</body>
</html>
