<?php
// First, set the action on the form
$this->form->setAction($this->url(array('action' => 'modify')));
echo "<h3>Modify an existing tipocategoria item</h3>";
echo $this->form;

echo "<a href='/admin/tipocategoria/addcategoria/tipocategoriaid/".$this->tipocategoriaid."/'>Add categorias</a>";
echo $this->render('/tipocategoria/indexcategorias.phtml');

//#BlockStart number=96 id=_Cx0PkKw9Ed68D_d-n4iFew_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=96
