drop table email
drop table log
drop table login
drop table dados_pessoais
drop table pessoas_perfis
drop table pessoa
drop table perfil
drop table mensagem_email
drop table anexo_mensagem
drop table mensagem
drop table categoria
drop table tipo_categoria