<?php
echo "<H3>list of all termcategory items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>name</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->termcategory_items as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->name</TD>";
    echo "<TD class='admin'><a href='/admin/termcategory/modify/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/termcategory/delete/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=100 id=_16_5_1_40d01a2_1250796837055_124877_421_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=100
