<?php
echo "<H3>list of all geradoruniqueid items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->geradoruniqueid_items as $item)
{
    echo "<TR>";

    echo "<TD class='admin'><a href='/admin/geradoruniqueid/modify/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/geradoruniqueid/delete/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=133 id=_SQ_mYK0ZEd6Tgc0yakCadQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=133
