<?php

// verificando se foi passado o titulo da view, no cabecalho
if (isset($this->cabecalho['tituloView'])) {
	// imprimindo titulo
	echo "<h3>" . $this->cabecalho['tituloView'] . "</h3>";
}

// verificando se foi passado o subtitulo da view, no cabecalho
if (isset($this->cabecalho['subtituloView'])) {
	// imprimindo subtitulo
	echo "<h4>" . $this->cabecalho['subtituloView'] . "</h4>";
}

// verificando se foi passado a mensagem da view, no cabecalho
if (isset ( $this->cabecalho ['mensagemView'] )) {
	// imprimindo mensagem
	echo "<h5>" . $this->cabecalho['mensagemView'] . "</h5>";
}

// verificando se foi passado o form da view
if (isset ($this->form)) {
	// carregando o form na view
	echo $this->form;

	// setando o foco para o primeiro elemento do formulario
	Basico_OPController_UtilOPController::setaFocusElementoFormularioViaJavaScript(Basico_OPController_UtilOPController::retornaNomePrimeiroElementoFormulario($this->form));

	// recuperando o tipo de container que agraga os subformularios do formulario, caso o formulario possuia filhos
	$tipoContainerFormulario = Basico_OPController_UtilOPController::retornaTipoContainerFormulario($this->form);

	// verificando se eh preciso setar funcao para setar focus
	if ($tipoContainerFormulario) {
		// setando funcao para setar o focus para o primeiro elemento de uma aba selecionada, para um formulario com subformularios
		Basico_OPController_UtilOPController::setaFocusPrimeiroElementoFormularioEmSelectChildFormularioComAbasViaJavaScript($this->form->getName(), $tipoContainerFormulario);
	}
}

// verificando se foi passado o titulo da view, no rodape
if (isset ($this->rodape['tituloView'])) {
	// imprimindo titulo
	echo $this->rodape['tituloView'];
}

// verificando se foi passado o subtitulo da view, no rodape
if (isset ($this->rodape['subtituloView'])) {
	// imprimindo o subtitulo
	echo $this->rodape['subtituloView'];
}

// verificando se foi passado a mensagem da view, no rodape
if (isset ($this->rodape['mensagemView'])) {
	// imprimindo a mensagem
	echo $this->rodape['mensagemView'];
}