<?php
require_once 'Zend/Json.php';

$arrayScripts        = array();
$modules 		     = null;
$dijits 		     = null;
$zendFormsMessages   = null;
$arrayHtmlElements   = array();
$existeFormNoRequest = null;
$idResponseSource	 = null;

// percorre as variáveis e objetos contidas na view
foreach ($this->getVars() as $keyVarView => $valueVarView){

	// verifica se a variável é do tipo array.
	if (is_array($valueVarView)) {
		
		// percorre o array enviado da view 
		foreach ($valueVarView as $key => $value) {
			
			if ($keyVarView === 'scripts') {
				$arrayScripts[] = $value;
				continue;
			}
			
			// se o conteúdo da possição percorrida não for um objeto, carrega o conteúdo no array $html[]. 
			if (!is_object($value)) {
				
				$arrayHtmlElements = Basico_OPController_UtilOPController::concatenaConteudoChaveArray($arrayHtmlElements, $keyVarView, $value);
			} else {

				// verifica se existe objetos do tipo formulário na view
				if (is_object($value) and is_subclass_of($value, 'Zend_Form')) {
						
					// verifica se existe subforms no formulário
					if ($value->getSubForms()) {
						
						// percorre os subforms
						foreach ($value->getSubForms() as $subForm) {						
							
							// processando formulario
							//$dados = processaForm($subForm, $this->dojo());
							$dados = Basico_OPController_UtilOPController::processaZendDojoForm($subForm, $this->dojo());

							// carregando dados processados...
							if (isset($dados['existeFormNoRequest'])) {
								$existeFormNoRequest = $dados['existeFormNoRequest'];
							}
							if (isset($dados['arrayScripts'])) {
								$arrayScripts = $arrayScripts + $dados['arrayScripts'];
							}
							if (isset($dados['zendFormsMessages'])) {
								$zendFormsMessages = $dados['zendFormsMessages'];
							}
							if (isset($dados['idResponseSource'])) {
								$idResponseSource = $dados['idResponseSource'];
							}
						}
						
					} else {
						// processando formulario
						//$dados = processaForm($value, $this->dojo());
						$dados = Basico_OPController_UtilOPController::processaZendDojoForm($value, $this->dojo());

						if (isset($dados['existeFormNoRequest'])) {
							$existeFormNoRequest = $dados['existeFormNoRequest'];
						}
						if (isset($dados['arrayScripts'])) {
							$arrayScripts = $arrayScripts + $dados['arrayScripts'];
						}
						if (isset($dados['zendFormsMessages'])) {
							$zendFormsMessages = $dados['zendFormsMessages'];
						}
						if (isset($dados['idResponseSource'])) {
							$idResponseSource = $dados['idResponseSource'];
						}
					}
					
					// se não existir forms no request, renderiza o formulario em html, para devolver ao cliente 
					if (!$existeFormNoRequest) {
						$arrayHtmlElements = Basico_OPController_UtilOPController::concatenaConteudoChaveArray($arrayHtmlElements, $keyVarView, $value->render());
					}
				}
			}
		}
	} else{
		
		// escreve conteúdo do javascript
		if ($keyVarView === 'scripts') {
			$arrayScripts[] = $valueVarView;
		}
		
		// escreve conteúdo do elemento html.
		$arrayHtmlElements = Basico_OPController_UtilOPController::concatenaConteudoChaveArray($arrayHtmlElements, $keyVarView, $valueVarView);		
	}
}

// se não existir formulario(s) no reques, carrega os módulos dos formularios
if (!$existeFormNoRequest) {
	// carrega os módulos do dojo necessarios aos formulários.
	$modules = $this->dojo()->getModules();
	
} else {
	$arrayHtmlElements = null;
}

// carregando os dijits. 
$dijits = $this->dojo()->getDijits();

// carregando title, script e link do header
$header['title']  = $this->headTitle()->toString();
$header['link']   = $this->headLink()->toString();
$header['script'] = $this->headScript()->toString();

// verificando se o ambiente é desenvolvimento.
if (Basico_OPController_UtilOPController::ambienteDesenvolvimento()) {
	// setando o footer com o debug info.
	$arrayHtmlElements['footer'] = ($this->render('footer.phtml'));
}

// monta resposta para o cliente...
$response = array('view' => array('header'            => $header,
								  'scripts'           => $arrayScripts,
								  'modules'           => $modules,
								  'dijits'            => $dijits,
								  'idResponseSource'  => $idResponseSource,
								  'zendFormsMessages' => $zendFormsMessages,
								  'html'  		      => $arrayHtmlElements,
								 ),
				 );

echo Zend_Json::encode($response);