<?php
echo "<H3>list of all login items</H3>";
$this->form->setAction($this->url(array('action' => 'index')));
echo $this->form;
echo "<TABLE class='admin'>";
echo "<TR>";
echo "<TD class='header'>login</TD>";
echo "<TD class='header'>senha</TD>";
echo "<TD class='header'>ativo</TD>";
echo "<TD class='header'>tentativasfalhas</TD>";
echo "<TD class='header'>travado</TD>";
echo "<TD class='header'>resetado</TD>";
echo "<TD class='header'>datahoraultimologon</TD>";
echo "<TD class='header'>observacoes</TD>";
echo "<TD class='header'>podeexpirar</TD>";
echo "<TD class='header'>datahoraproximaexpiracao</TD>";
echo "<TD class='header'>datahoraultimaexpiracao</TD>";

echo "<TD class='header'>modify</TD>";
echo "<TD class='header'>delete</TD>";
echo "</TR>";
foreach($this->login_items as $item)
{
    echo "<TR>";

    echo "<TD class='admin'>$item->login</TD>";
    echo "<TD class='admin'>$item->senha</TD>";
    echo "<TD class='admin'>$item->ativo</TD>";
    echo "<TD class='admin'>$item->tentativasfalhas</TD>";
    echo "<TD class='admin'>$item->travado</TD>";
    echo "<TD class='admin'>$item->resetado</TD>";
    echo "<TD class='admin'>$item->datahoraultimologon</TD>";
    echo "<TD class='admin'>$item->observacoes</TD>";
    echo "<TD class='admin'>$item->podeexpirar</TD>";
    echo "<TD class='admin'>$item->datahoraproximaexpiracao</TD>";
    echo "<TD class='admin'>$item->datahoraultimaexpiracao</TD>";
    echo "<TD class='admin'><a href='/admin/login/modify/id/$item->id'>modify</a></TD>";
    echo "<TD class='admin'><a onClick='return confirm(\"are you sure you want to delete this object\");' href='/admin/login/delete/id/$item->id'>delete</a></TD>";
    echo "</TR>";
}
echo "</TABLE>";

//#BlockStart number=16 id=_nhohcKoDEd687LtTWUTtuQ_#_0
      
//start block for manually written code
        
//end block for manually written code

//#BlockEnd number=16
